//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePayment_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public long UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<int> DistID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
